#!/usr/bin/env bash

# based on ~/rush-repos/dannyben/rush-repo/common.sh
source ../common.sh

# based on dannyben:gitconfig
say "configuring git"
cp .gitignore_global ~/
cp .gitattributes_global ~/

git config --global push.default simple
git config --global color.ui true
git config --global core.editor vi
git config --global core.autocrlf input
git config --global credential.helper "cache --timeout=21600"
git config --global core.excludesfile ~/.gitignore_global
git config --global core.attributesfile ~/.gitattributes_global

# based on dannyben:my/gitconfig
say "applying personal git configuration"
git config --global user.name "Uri Benchetrit"
git config --global user.email uribench@gmail.com
