#!/usr/bin/env bash
source ../common.sh

say "installing essential rush packages"

# essential packages copied from dannyben:bootstrap
needs bashrc-global
needs dircolors
needs exrc
needs inputrc
needs irbrc

# additional essential packages 
needs opcode
needs direnv
needs ssh-agent
needs cdpath
needs gitconfig
needs alf
needs locale

say "bootstrap complete"
attention "you may need to restart your session"
