#!/usr/bin/env bash
source ../common.sh

say "installing essential rush packages"

# essential packages copied from dannyben:bootstrap
needs dannyben:bashrc
needs dannyben:dircolors
needs dannyben:exrc
needs dannyben:inputrc
needs dannyben:irbrc

# additional essential packages 
needs dannyben:opcode
needs dannyben:direnv
needs dannyben:ssh-agent
needs cdpath
needs gitconfig
needs alf

say "bootstrap complete"
attention "you may need to restart your session"
