#!/usr/bin/env bash
source ../common.sh

say "installing Tangram Python library"
# Upgrade pip to resolve the installation issue of "Could not find a version that satisfies the requirement..."
# Note: this problem exists both in bionic (Ubuntu 18.04.5 LTS) and focal (Ubuntu 20.04.2 LTS)
pip install --upgrade pip

# Apply changes
# shellcheck disable=SC1090
source ~/.profile

# Install Tangram Python library
pip install tangram

attention "restart your session or source ~/.profile to apply changes"